### Download dataset


In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("uciml/sms-spam-collection-dataset")

print("Path to dataset files:", path)

/Users/hrishi/Desktop/InterviewPrep/ai/.venv/lib/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


Path to dataset files: /Users/hrishi/.cache/kagglehub/datasets/uciml/sms-spam-collection-dataset/versions/1


### Load dataset and prepare DataFrame


In [2]:
import pandas as pd
import os

path2 = os.path.join(path, 'spam.csv')
print(path2)
messages = pd.read_csv(os.path.join(path, 'spam.csv'), usecols=['v1','v2'], encoding='latin1').rename(columns={'v1': 'label', 'v2': 'message'})

messages = messages[messages['label'] != 'v1']




/Users/hrishi/.cache/kagglehub/datasets/uciml/sms-spam-collection-dataset/versions/1/spam.csv


### Import regular expressions and NLTK stopwords


In [3]:
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/hrishi/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

### Import stopwords and Porter stemmer


In [4]:
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

### Preprocess SMS messages into a stemmed corpus


In [5]:
ps = PorterStemmer()
corpus = []
for i in range (0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['message'][i]) # replace non-alphabetic with space

    review = review.lower()

    review = review.split()

    review = [ ps.stem(word) for word in review if word not in stopwords.words("english")]

    review = ' '.join(review)

    corpus.append(review)

print(corpus[:5])  # print first 5 to check

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat', 'ok lar joke wif u oni', 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli', 'u dun say earli hor u c alreadi say', 'nah think goe usf live around though']


### Convert corpus to bag-of-words vectors


In [6]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(binary=False, max_features=500)

X = cv.fit_transform(corpus).toarray()
print(X)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [12]:
##

cvBigram = CountVectorizer(binary=True, max_features=500, ngram_range=(1,2))

X1 = cvBigram.fit_transform(corpus).toarray()

print(cvBigram.vocabulary_)

{'go': np.int64(154), 'point': np.int64(332), 'great': np.int64(164), 'world': np.int64(483), 'got': np.int64(162), 'wat': np.int64(463), 'ok': np.int64(297), 'lar': np.int64(217), 'wif': np.int64(473), 'free': np.int64(141), 'entri': np.int64(125), 'win': np.int64(475), 'final': np.int64(134), 'st': np.int64(400), 'may': np.int64(253), 'text': np.int64(415), 'receiv': np.int64(354), 'question': np.int64(345), 'txt': np.int64(446), 'rate': np.int64(347), 'appli': np.int64(18), 'dun': np.int64(114), 'say': np.int64(368), 'earli': np.int64(116), 'alreadi': np.int64(9), 'think': np.int64(421), 'goe': np.int64(156), 'live': np.int64(235), 'around': np.int64(20), 'though': np.int64(423), 'hey': np.int64(187), 'week': np.int64(466), 'word': np.int64(481), 'back': np.int64(29), 'like': np.int64(231), 'fun': np.int64(148), 'still': np.int64(403), 'xxx': np.int64(490), 'send': np.int64(376), 'even': np.int64(126), 'brother': np.int64(46), 'speak': np.int64(398), 'per': np.int64(313), 'set': np.

In the above cell output we will she the word with the index, for example word with index 1 has the highest occurance. 

In [14]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [17]:
tfidf = TfidfVectorizer(max_features=100)
X_tfidf = tfidf.fit_transform(corpus).toarray()
tfidf.vocabulary_

{'go': np.int64(22),
 'great': np.int64(25),
 'got': np.int64(24),
 'wat': np.int64(90),
 'ok': np.int64(57),
 'free': np.int64(18),
 'win': np.int64(94),
 'text': np.int64(77),
 'txt': np.int64(86),
 'say': np.int64(68),
 'alreadi': np.int64(0),
 'think': np.int64(80),
 'hey': np.int64(28),
 'week': np.int64(92),
 'back': np.int64(4),
 'like': np.int64(39),
 'still': np.int64(73),
 'send': np.int64(70),
 'even': np.int64(15),
 'friend': np.int64(19),
 'prize': np.int64(63),
 'claim': np.int64(8),
 'call': np.int64(5),
 'mobil': np.int64(48),
 'co': np.int64(9),
 'home': np.int64(30),
 'want': np.int64(89),
 'today': np.int64(82),
 'cash': np.int64(7),
 'day': np.int64(12),
 'repli': np.int64(65),
 'www': np.int64(96),
 'right': np.int64(66),
 'thank': np.int64(78),
 'take': np.int64(75),
 'time': np.int64(81),
 'messag': np.int64(45),
 'oh': np.int64(56),
 'ye': np.int64(97),
 'make': np.int64(43),
 'way': np.int64(91),
 'feel': np.int64(16),
 'dont': np.int64(14),
 'miss': np.int64(4